### ISSUE TITLE
Request Bandcamp API access for LastToFire

### ISSUE THREAD

**Issue by JonLeeCon** [JonLeeCon/GetSteady#1]
Contact them (https://bandcamp.com/contact?subj=API%20Access) and include in your email a brief description of how you intend to use API access

Source: https://bandcamp.com/developer

**Comment by RealEvanPonter** [comment]
Sent email on 3/12/17

**Comment by RealEvanPonter** [comment]
Bandcamp is not granting API access to anyone but Label Accounts. See their response below:

> Thanks for your interest. Our APIs are currently limited to Label Accounts (bandcamp.com/labels) looking to pull physical order and general sales information, though that might change down the road. Please keep an eye on bandcamp.com/developer for updates.
> 
> Cheers,
> Bryan
> Bandcamp

@JonLeeCon Should we continue to use their player but with the iFrame they offer? Or look for a different way to do this?

**Comment by RealEvanPonter** [comment]
Ok. It looks like [Sound Cloud has an API](https://developers.soundcloud.com/docs/api/guide#playing) we could use. The only downside to that is they don't have a "give the band money when you download their music" option.

So we could get fancy and just include the Bandcamp download link as an attribute for each album. As long as we name the album the same thing on both Bandcamp and Soundcloud, we can predict the URLs.

Example:

1. We would request all the songs from all of the public albums/EPs on our Soundcloud account via their API and store the data in our model - Album name, Album URL, **Bandcamp Link** (use a function to derive this from the Album URL attribute), Songs: [ song name, song URL, album name, track number, etc ]
2. For the Mirror Ball EP on Soundcloud, the URL for that album is https://soundcloud.com/lasttofire/sets/**mirror-ball-ep**
3. For the Mirror Ball EP on Bandcamp, the download URL is http://lasttofire.bandcamp.com/album/**mirror-ball-ep**?action=download&from=embed
4. We would play the music using the Soundcloud API, but include a "Download" hyperlink that directs the user to the album on Bandcamp

**Comment by JonLeeCon** [comment]
I think this is the way to go for now
