### ISSUE TITLE
Specify color scheme

### ISSUE THREAD

**Issue by RealEvanPonter** [JonLeeCon/GetSteady#5]
Get the RGB codes for each color of the color scheme

**Comment by JonLeeCon** [comment]
@RealEvanPonter can you confirm that the colors I have on the wiki are the same as the ones Shannon did?

**Comment by RealEvanPonter** [comment]
Ok I spent some time comparing all the colors and using different converters. I think the Pantone colors and the CMYK that Shannon gave me ensure that when you print the colors, they look like what you see on the screen. But if you use those codes for the web, they all look brighter. The RGB hex codes you got (apparently there are CMYK Hex codes as well?) will work. Or you can use the RGB codes I put in there. Let me know if you need anything else on this one
